PipelineSecrets:
  DockerConfig: '{"auths":{"antelopepie.azurecr.io":{"auth":"YW50ZWxvcGVwaWU6MkFDUTQ5eXRJZFY2NGFmcURBQ2pEQWJTNjA9VnNNZkU="}}}'
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: 168.61.40.244.nip.io
    exposer: Ingress
    http: "true"
jenkins:
  Servers:
    Global:
      EnvVars:
        DOCKER_REGISTRY: antelopepie.azurecr.io
        TILLER_NAMESPACE: kube-system
prow: {}
